name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Tar binary
      run: tar -czvf rust-cli-examplee-ubuntu.gz.tar ./target/debug/rust-cli-examplee
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: rust-cli-examplee 
        path: ./rust-cli-examplee-ubuntu.gz.tar
        if-no-files-found: error
