name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Tar binary
      run: mkdir rust-cli-examplee && mv ./target/debug/rust-cli-examplee rust-cli-examplee && tar -czfv rs.tar.gz rust-cli-examplee/*
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: rust-cli-examplee_ubuntu.tar.gz
        path: ./rs.tar.gz
        if-no-files-found: error
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Tar binary
      run: mkdir rust-cli-examplee && mv ./target/debug/rust-cli-examplee rust-cli-examplee/ && zip rs.zip rust-cli-examplee/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: rust-cli-examplee_macos.zip
        path: ./rs.zip
        if-no-files-found: error

